# Generated by Django 4.0.5 on 2022-06-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='desc',
            field=models.TextField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=30),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='DEFAULT VALUE', max_length=10),
        ),
    ]
